name: "Poker face guy"
default-state:
    type: "idling"
    name: "Serious"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2UwYTJlMmZmNGNhYzE3MDJkOWE5ODBlZjk5ZTk5MDQzMzM4YmI3Zjg1MmNiNjE2MDRmNzRhNjI5NTU0NzY2NSJ9fX0="
states: []